### ISSUE TITLE
The `npm version` command results to an error

### ISSUE THREAD

**Issue by cermakjiri** [AckeeCZ/changelog-it#1]
When I run `npm version patch`, I get following error:
```
> changelog-it && vim CHANGELOG.md && git add CHANGELOG.md

Generating record
<pathToMateus>/mateus/node_modules/keep-a-changelog/src/parser.js:11
        throw new Error(`Parse error in the line ${tokens[0][0]}: ${error.message}`);
        ^

Error: Parse error in the line 14: Invalid change type
    at parser (<pathToMateus>/mateus/node_modules/keep-a-changelog/src/parser.js:11:15)
    at Object.<anonymous> (<pathToMateus>/mateus/node_modules/changelog-it/src/changelog.js:13:19)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (<pathToMateus>/mateus/node_modules/changelog-it/index.js:1:63)
```

I've tried to reinstall node modules, but with the result is still the same.

**Comment by horaklukas** [comment]
according to the keep-a-changelog standard, `Updated` [isnt a valid heading keyword](https://keepachangelog.com/en/1.0.0/#how), it's supossed to be `Changed` instead. So I guess this record in changelog was made manually, anyway, I will try to handle that case in `changelog-it`.
